### ISSUE TITLE
capitalization doesnt play well with special char

### ISSUE THREAD

**Issue by sandrotosi** [keithgg/puddletag#265]
When I'm capitalizing any text, things like

some text (other text here)

gets capitalized as

Some Text (other Text Here)

note the 'other' is still lowercase, and the same happen with text close to other special chars, like the single quote (') which is ok in cases like "don't" -> "Don't" but no for "name 'alias' surname" which should be "Name 'Alias' Surname"

**Comment by keithgg** [comment]
Where are you using the capitalization from? In the Case Conversion function you can specify the characters that trigger a capital letter.

**Comment by sandrotosi** [comment]
Oh, you're right: I created that rule a long ago and didnt remember we could specify the chars, just  verified, it works as expected - closing
