### ISSUE TITLE
Ordering the Tag Panel seems to be broken/unefficient

### ISSUE THREAD

**Issue by chincheta0815** [keithgg/puddletag#272]
When customizing the tag panel, one can use the up and down arrow for moving an entry.
However, the program only recognizes the info in the row column by a specific number.

Changing the order can be really hard...

By the way: There is a "Al&bum" typo... When correcting that it changes the below "Track" to "Tr&ack". Is that on purpose?

**Comment by keithgg** [comment]
See http://puddletag.sourceforge.net/source/preferences.html#tag-panel for explanation of the & symbol.

I know the layout is horrible, but too pressed for time to fix it. Closing issue.
