### ISSUE TITLE
Can't modify tags on files loaded over SFTP

### ISSUE THREAD

**Issue by edent** [keithgg/puddletag#274]
I'm accessing a directory on a remote server.  In the `dirpath` I see

`[{"__dirpath": "/run/user/1000/gvfs/sftp:host=example.com,port=123,user=edent/Music/Vancouver"}]`

I can load the files, but when I try to edit the tags the file isn't changed.  What is weird is that the file creation date is updated.

Other applications on my desktop are able to write to files on this network share.

Running Ubuntu 14.04 and PuddleTag 1.0.5.

I think this is related to #110.

**Comment by keithgg** [comment]
Not sure why it'd fail. I'd suggest creating a soft link to the folder with a more correct path (without colons and stuff).

Closing the issue as it's unlikely that I'll ever do any work on it. Re-open if you have more to add.
