### ISSUE TITLE
[Feature Request] Custom, persistent column widths between sessions

### ISSUE THREAD

**Issue by Miclmeo** [keithgg/puddletag#281]
Right now, when Puddletag is opened, it arranges the width of the columns in the tag field matrix (however that's called) with one of two principles (afaik):

1. Make every column the same width. This is obviously not optimal, as i.e. the "Track" column needs less space than "Title".

2. Intelligent width, whatever that is. All i know is that it doesn't always deliver good results, and I usually change the widths manually after that.

Problem here is that after carefully rearranging the column widths, they get reset every restart or even when adding a new column, which messes up my fine-tuned setup ;)

Proposal is to have an option to remember the custom width of every column, whether visible or not, and keep that one until it is manually resized or one of the automatic resizing modes is chosen.

**Comment by keithgg** [comment]
Uncheck the option to automatically [resize column widths in your preferences](http://docs.puddletag.net/source/preferences.html#automatically-resize-columns-to-contents). Then it will be completely manual (and preserved on restarts).

Re-open issue if it's not working for you.
