### ISSUE TITLE
[v1.1.0] Cannot start puddletag

### ISSUE THREAD

**Issue by hameau** [keithgg/puddletag#283]
Hello,

This version of puddletag fails to start for me. From the cli:
```
~$ puddletag
Traceback (most recent call last):
  File "/usr/bin/puddletag", line 333, in <module>
    print_info()
  File "/usr/bin/puddletag", line 289, in print_info
    from puddlestuff import version_string, changeset
ImportError: cannot import name changeset
```
Running on Debian Jessie amd64; .deb installed with dpkg over previous v1.0.5

**Comment by keithgg** [comment]
Hi there

I've uploaded a new release that should fix the issue.

https://github.com/keithgg/puddletag/releases/download/1.1.1/puddletag_1.1.1-1_all.deb
