### ISSUE TITLE
Tag source Amazon returns invalid XML

### ISSUE THREAD

**Issue by Logout22** [keithgg/puddletag#286]
Whenever I try to retrieve tags or cover art from Amazon, I receive an "Invalid XML returned" error.

System: Gentoo, puddletag 1.1.1
Also tried current git master.

Thanks!

**Comment by keithgg** [comment]
Seems to work for me. Can you provide any examples of what you're searching for?

**Comment by Logout22** [comment]
I removed the app a while ago and use Picard and MP3Tag via Wine instead. Sorry!
