### ISSUE TITLE
How to remove menu items after adding them through the Actions screen? 

### ISSUE THREAD

**Issue by spectromas** [keithgg/puddletag#287]
I'm sorry if this is documented but I can't find anything for it. I created a menu item under Actions by going to Actions>Actions>Assign Shortcut (edit name and add a shortcut). This created a shortcut entry under Actions. I would like to remove one of the entries listed under the main Actions menu (underneath the default Actions, Quick Actions, Functions) but I can't seem to find a way to do it, the menu items don't correspond to what is under the Actions>Actions menu box. I looked through the config files in ~/.config/puddletag but I can't see anything in those either. 
Am I missing something obvious? 

I've attached picture in case this isn't clear. I want to remove the duplicate 'Move to Downloaded Tunes' and the test entry. 
![2016-02-21-133021_1366x768_scrot](https://cloud.githubusercontent.com/assets/6443372/13204842/6587c5ca-d89f-11e5-89d1-e37ca2ecd36c.png)

**Comment by keithgg** [comment]
On the actions dialog click and hold on the "Assign Shortcuts" button. In the opened dialog you can add/edit any of the menu items.

**Comment by spectromas** [comment]
Thank you so much for the information @keithgg
