### ISSUE TITLE
Puddletag AppImage 

### ISSUE THREAD

**Issue by kskarthik** [keithgg/puddletag#288]
[Appimage](http://appimage.org) helps packing apps which can run on all major Linux distributions. It's based on concept of **one app = one file**

If puddletag can be packed along with all its dependencies inside an appimage, users can simply download give permission & run the file. Appimage also supports Delta updates.

Popular apps like subsurface, scribus, krita also adopted this method to distribute their apps. It's easy to pack apps using AppImage. No extra knowledge required.

Project repo: https://github.com/probonopd/AppImagekit

The developer @probonopd is happy to help you packing your app :)

**Comment by keithgg** [comment]
I'm gonna pass on this. Happy to receive a pull request though. ;-)

**Comment by kskarthik** [comment]
@keithgg may be this could help you https://github.com/probonopd/AppImageKit/wiki/Bundling-Python-apps

**Comment by probonopd** [comment]
Can puddletag be installed into a [virtual environment](https://virtualenv.pypa.io/en/stable/) or be bundled with [cx_freeze](https://pypi.python.org/pypi/cx_Freeze)?

**Comment by keithgg** [comment]
Nope, since it depends on PyQt4 which as far as I know doesn't support pip installation.

In theory it should work with cx_freeze, but I didn't really check.

**Comment by probonopd** [comment]
Wasn't too hard:
https://github.com/probonopd/AppImages/blob/master/recipes/meta/Puddletag.yml

Here is the AppImage, it is using the deb from the GitHub Releases page.
https://bintray.com/probono/AppImages/puddletag/_latestVersion#files

**Comment by karsta62** [comment]
This is old, but so is beloved puddletag.
As I stated in #454 as well, this image does not work in Ubuntu 20.04:

./puddletag-1.1.1.glibc2.15-x86_64.appimage 
Traceback (most recent call last):
  File "/tmp/.mount_3IShgP/usr/bin/puddletag", line 317, in <module>
    from PyQt4.QtGui import QApplication, QPixmap, QSplashScreen, QIcon
ImportError: /usr/lib/x86_64-linux-gnu/libfontconfig.so.1: undefined symbol: FT_Done_MM_Var

Isn't this just what should not happen with these images?
It works with 18.04.

**Comment by probonopd** [comment]
Yes, this is a bug with that old experimental AppImage. https://github.com/keithgg/puddletag should make a proper one... I'm here to help.

**Comment by miniworm** [comment]
Proper appimage has been created, please check #464

**Comment by sandrotosi** [comment]
Please check #468

**Comment by probonopd** [comment]
> Proper appimage has been created, please check #464

Thanks @miniworm could it be uploaded to
https://github.com/keithgg/puddletag/releases
please?

**Comment by miniworm** [comment]
From me perspective it’s more than welcomed. But I’m not puddletag maintainer so I cannot do it myself. Let’s hope for this, maybe @keithgg can help? We prepared appImage, no it’s only simple administrative task.

**Comment by keithgg** [comment]
Thanks for the effort guys. 

I'll check out the AppImage and upload it this weekend if all good.

**Comment by miniworm** [comment]
Thanks @keithgg . If you'll find this appimage OK maybe it would be also good to provide info about it on main puddletag webpage in Downloads section ( [http://docs.puddletag.net/download.html](http://docs.puddletag.net/download.html) ) since now it has no reference to github releases page ( [https://github.com/keithgg/puddletag/releases](https://github.com/keithgg/puddletag/releases) ) and for sure some people will try to find info there and will see currently incorrect info that for example for Ubuntu they should use WebUpd8 PPA.

**Comment by dmidecodes** [comment]
> I'll check out the AppImage and upload it this weekend if all good.

quick question, does there exist an official appimage version - i could not find anything related in the releases section?

thanks a lot.

**Comment by sandrotosi** [comment]
> > I'll check out the AppImage and upload it this weekend if all good.
> 
> quick question, does there exist an official appimage version - i could not find anything related in the releases section?

There's no official appimage version of puddletag supported by the puddletag development team
