### ISSUE TITLE
python support in new ubuntu

### ISSUE THREAD

**Issue by Pastim** [keithgg/puddletag#290]
I installed xubuntu 16.04 recently.  puddletag won't install because python-support is no longer available.

It seems they are moving to only support python 3 and I believe puddletag needs 2.7.

I managed to get around it (by temporarily adding a debian 8 jessy ppa) so I'm OK for now.

However, if the writing truly is on the all for older python, is there any chance of puddletag moving to python 3?

**Comment by thwaller** [comment]
I have the same issue. 16.04 is an official LTS release that all users are directed to as the default download for desktop purposes: http://www.ubuntu.com/download/desktop. As much as I like it, this kind of depreciates puddletag unless updated.

**Comment by Pastim** [comment]
I don't just 'like' it - it's essential!  Nothing else on linux comes close.

Having said that I have no idea if this is a lot of work or not.  My coding skill are very limited, so I daren't suggest helping with that.  However, I'd be happy to be an alpha tester if that would help, or do anything else that would assist.

**Comment by keithgg** [comment]
It should be possible to work around it. I'll take a look when I get time.

In the mean time you might have better luck using the WebUpd8 ppa: https://launchpad.net/~webupd8team/+archive/ubuntu/puddletag

**Comment by Pastim** [comment]
That sounds excellent.  I'll be migrating my main desktop to ubuntu 16.04 soon (once I summon up the courage) so I'll try that ppa then.

**Comment by thwaller** [comment]
Installing from the Software Center from within 16.04 will also work.

**Comment by Pastim** [comment]
On xubuntu 16.04 puddletag does not appear in 'Software Center', not least because that no longer exists (on a fresh install at least).  It's now 'Software', and there's no puddletag.

**Comment by thwaller** [comment]
I am using "Release 16.04 LTS (Xenial Xerus) 64-bit". For me it is in "Ubuntu Software Center".

**Comment by Pastim** [comment]
If you upgraded rather than reinstalled you have probably kept the Ubuntu Software Center,  Sadly that isn't true for a fresh (x)ubuntu install.  Do you also have python 2.7 installed?

**Comment by thwaller** [comment]
This was a fresh install of Ubuntu. Try "apt-get install software-center". I have never done an upgrade, just updates. When an upgrade is needed, I migrate instead. 2.7 and 3.5 were installed on the initial install, by default. When I used the download deb installer, it needed python-support, which is depreciated. After attempting to install the downloaded deb and receiving this error, I went to Software Center and did the install there. It worked without additional install. The package "python-support" is not installed on my system. Xubuntu is a lite, this may be the issue. I have noticed on some test systems that Software Center was not there, especially on the lite flavors. I believe Lubuntu is one of them too, but if I recall, they have a special Software Center for that one. They are all the same really, just different default packages. On this system I am running MATE.

**Comment by Pastim** [comment]
OK - thanks for the information.

**Comment by Pastim** [comment]
I have been installing a fresh ubuntu 16.04 on my main desktop, and can confirm all that thwaller said.   puddletag installs OK from the ppa.

**Comment by funkyfuture** [comment]
i don't see any reason that an application shouldn't have been ported to Python 3 in the year 2016.

**Comment by Pastim** [comment]
Because it's free, it still works, and the creator may have other, better things to do with his or her time?  

I'm just immensely grateful puddletag exists and is as good as it is.  It would be great if was ported to python 3 before 2.7 disappears from current systems altogether, but nothing lasts for ever.

**Comment by vmorris** [comment]
Me too

**Comment by eson57** [comment]
First of all, the _python-support_ package seem to be replaced by _dh-python_. If you need python-support, there is a .deb that works just fine.
`wget http://launchpadlibrarian.net/109052632/python-support_1.0.15_all.deb`

**Comment by keithgg** [comment]
Closing this issue until someone else is willing to take up the work to do this (or point me to a super simple guide that I can follow). It's more complicated building the package on Ubuntu than it needs to be. 

For now just use the webupd8 ppa which keeps up to date with any new releases fairly quickly. https://launchpad.net/~nilarimogard/+archive/ubuntu/webupd8
