### ISSUE TITLE
Tagging/Mass tagging based on already existing MB album id

### ISSUE THREAD

**Issue by zuzzurro** [keithgg/puddletag#292]
I would like to update/complete/refresh the tags/covers of files that I have already tagged with picard.
I can manually search using :b for a specific album id, but I would like the search to happen automatically without me having to supply a value that is already in the file in the first place. Is there a way to do it that I am missing?

**Comment by keithgg** [comment]
If the **mbrainz_album_id** tag is valid it should get used automatically when you do a search (no need to add or filter anything).

**Comment by zuzzurro** [comment]
Would it be possible for you to tell me the lines and the module that do this? As all the tools for managing audio/tags are in python I may have to end up learning it if I want to contribute...
