### ISSUE TITLE
[FEATURE REQUEST] I propose to add a few features

### ISSUE THREAD

**Issue by KOT040188** [keithgg/puddletag#299]
I apologize for using google translate. I really like puddletag, but the lack of some features prevent me to use it.
1. I really needed to group files in folders like the picture on the link https://dl.dropboxusercontent.com/u/85152410/ss/ss_2016.07.07_07%3A07%3A15.png. It looks like tagscanner running under wine. If you double-click on the group name will highlight all files in this group.
2. I need to select files in the list with the left mouse button. This is done in the above mentioned tagscanner and qbittorrent.
Without these functions it is very difficult to use puddletag. Thank you.

**Comment by keithgg** [comment]
I'm not interested in adding a view like that (happy for a pull request though), so closing this.

For similar functionality, sort by dirname or dirpath. Then use Select Next Dir (http://docs.puddletag.net/source/menus.html#select-next-dir-ctrl-n) to go through the folders.

**Comment by KOT040188** [comment]
Sad. Will have to use tagscanner under wine ☹
