### ISSUE TITLE
Spanish translation in process

### ISSUE THREAD

**Issue by josevidaldoblecero** [keithgg/puddletag#302]
Hello, for some years I use puddletag, I think it is very complete. For some time I am working in launchpad to translate some texts Inkscape to Spanish, I am a native in this language. So I thought to translate the application puddletag to Spanish. I read the information you have provided to make it and I now have the translation of approximately 30%. Even it take a few weeks to have it finished, as I like to see that the translation is accurate and coherent context.

Thank you for this useful application.

**Comment by keithgg** [comment]
That'd be awesome. Send a pull request when done. Thanks!

**Comment by keithgg** [comment]
Closing #308
