### ISSUE TITLE
Autonumbering Wizard does not apply padded zeros to total # of tracks.

### ISSUE THREAD

**Issue by ACasper21** [keithgg/puddletag#303]
Autonumbering Wizard does not apply padded zeros to total # of tracks when using that option, and when total number of track is less than when a zero would be needed.

For example:
With a total of 9 tracks and max length of 2 after padding with zeroes, track# tags will be:
01/9
02/9
03/9
...

I'm assuming this may not be the desired behavior.

**Comment by keithgg** [comment]
I just tried it and it alway added the padding. Are you on the latest version?
