### ISSUE TITLE
icons for buttons

### ISSUE THREAD

**Issue by josevidaldoblecero** [keithgg/puddletag#309]
Hi, most of the buttons have a representative icons of the action they perform. But there are a few who do not have an icon according to the design of others. I enclose a pack of 3 icons, for more information you think will contribute to current. Are distributed with a Creative Commons license, both PNG and SVG.
[icons.zip](https://github.com/keithgg/puddletag/files/441255/icons.zip)

**Comment by keithgg** [comment]
Hi there, thanks for this. Sorry about the late reply. I feel like the icons are a bit more confusing than what we currently have (decrease the size to the current puddletag icons and you'll see).

Have to reject unfortunately.
