### ISSUE TITLE
not retrieving cover art from discodogs

### ISSUE THREAD

**Issue by edendo** [keithgg/puddletag#310]
Hi,
I can't retrieve cover art from discodogs, the Artwork panel just stays <blank>, the album information itself is working flawlessy. With Amazon artwork is working though.
Any ideas?
Cheers

**Comment by keithgg** [comment]
Discogs placed some limits on their api. You can't get album art unless through OAuth2 and even then you're still limited.

I'm too lazy to implement (because I'd need to set up a server to communicate with Discogs). Closing for now.

**Comment by holms** [comment]
@keithgg  Can I get it from anywhere else? I don't see such functionality at all.
