### ISSUE TITLE
rename just case doesn't work on case insensitive fs

### ISSUE THREAD

**Issue by hboetes** [keithgg/puddletag#311]
My music storage is on an smb share, which is by definition case insensitive. Renaming files where just the case of a char is changed always fails since the underlying FS doesn't see a difference.

Could you set up a workaround that does something like the following pseudo code.

```
rand=random()
mv $oldfilename $newfilename.$rand
mv $newfilename.rand $newfilename
```

Perhaps there is an even more elegant solution, I just used the pseudo code to explain the problem.

**Comment by keithgg** [comment]
There's no elegant solution for this really. Isn't there some config option you can set in Samba?

**Comment by hboetes** [comment]
You’re right, this would be a work-around. This must be fixed with the cifs options.
