### ISSUE TITLE
ID3 Comment Tag Incorrect

### ISSUE THREAD

**Issue by doakey3** [keithgg/puddletag#314]
I noticed that in the [ID3 Tag reference](http://docs.puddletag.net/source/tags.html) it says that the tag for comments is 'COMM', but when I run mutagen and check the available tags for a file I've edited with puddletag, it says the comment tag is 'COMM::XXX'

For example, in python do:

```python
from mutagen.mp3 import MP3

mp3file = MP3("path to mp3 file")
print(mp3file.tag.keys())
```
This will output the tags for the file. If you've added a comment to the mp3 file with puddletag, you'll see the weird tag 'COMM::XXX' printed in the console.

**Comment by keithgg** [comment]
That mutagen. It's literally the library puddletag uses. COMM frames require a description and another field whose name escapes me now.

COMM fields without a description are interpreted as the comment field by most music players. Let me know if your music player interprets it incorrectly and I'll revisit this.
