### ISSUE TITLE
Question on Understanding Code Line.

### ISSUE THREAD

**Issue by chincheta0815** [keithgg/puddletag#316]
Can you please explaing me line 2310 in the file "source/puddlestuff/tagmodel.py".
`self.connect(header, SIGNAL('saveSelection'), self.saveSelection)`

All I figured out is, that it should look like (maybe wrong):
`header.saveSelection.connect(self.saveSelection)`

Python complains about the 'header' has no attribute 'saveSelection' (=Signal).

I am trying to convert this line for pyqt5 and python3 but I do not manage it.
The SIGNAL macro on pyqt5 is obsolete.
So I would appreciate it to get this example port.
This will help me for going on.

**Comment by keithgg** [comment]
There should be a saveSelection function on the TableHeader model. See line 2210 of the same file. The function is on the TagModel instance though. 

I haven't looked at the way signals work with PyQt5, but it in the end the header will send the saveSelection signal which will call TagModel.saveSelection.

**Comment by chincheta0815** [comment]
Is the saveSelection signal custom mmade implemented by you or part of PyQt? 
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 09.11.16, 19:21, Keith Grootboom <notifications@github.com> schrieb:

  
    
      There should be a saveSelection function on the TableHeader model. See line 2210 of the same file. The function is on the TagModel instance though.
    
    
      I haven't looked at the way signals work with PyQt5, but it in the end the header will send the saveSelection signal which will call TagModel.saveSelection.

**Comment by keithgg** [comment]
Custom implemented.

**Comment by chincheta0815** [comment]
in which part of the code?
running the code the signal is not found without problems... when i understood that i think it will be easier...
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 13.11.16, 08:02, Keith Grootboom <notifications@github.com> schrieb:

  
    
      Custom implemented.

**Comment by keithgg** [comment]
You can find the implementation here. https://github.com/keithgg/puddletag/blob/master/source/puddlestuff/tagmodel.py#L2202

**Comment by keithgg** [comment]
Closing this. They removed qt4 support from brew which broke it. Only way to install it now is from source. I don't use OSX, so can't help you out unfortunately. Further discussion to happen in #300
