### ISSUE TITLE
tag -> filename excluding brackets/parentheses

### ISSUE THREAD

**Issue by milothegreat** [keithgg/puddletag#317]
Is it possible to write a tag to the filename excluding the content of brackets/parentheses. In other words, is it possible to declare a filter in the pattern? I did not find this info in the doc.

example of what I mean/want:

title: trackname (feat. artists)

title tag -> filename

filename: trackname.mp3

Thanks a lot in advance.

**Comment by keithgg** [comment]
Not sure what you're looking for here. Text->Tag will probably suit your needs. http://docs.puddletag.net/source/function.html#text-to-tag
