### ISSUE TITLE
Wrong download link on website

### ISSUE THREAD

**Issue by rburgosnavas** [keithgg/puddletag#320]
The download for the tar file in http://docs.puddletag.net/download.html is incorrect; the URL is missing a "v" before the version number:
https://github.com/keithgg/puddletag/releases/download/1.2.0/puddletag-1.2.0.tar.gz

The correct URL is https://github.com/keithgg/puddletag/releases/download/v1.2.0/puddletag-1.2.0.tar.gz

**Comment by keithgg** [comment]
Thanks for reporting. Fixed.
