### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by neolovich** [keithgg/puddletag#321]
How do i uninstall puddletag? I installed it with the command `python setup.py install` for trying it.

**Comment by dglava** [comment]
It would have been better to create a proper package for your distribution, to allow easy package removal or updates.

Anyway, run setup.py again and check out the --record flag, which outputs all the files which are installed into a text file.
`python setup.py install --record files.txt`

**Comment by neolovich** [comment]
Thank you!

**Comment by dglava** [comment]
You should close this issue now since it's resolved.
