### ISSUE TITLE
[Migrating puddletag]: Kernel trap. Help appreciated.

### ISSUE THREAD

**Issue by chincheta0815** [keithgg/puddletag#322]
Hey,

I did some work on migrating puddletag to python3 and PyQt5.
The splash screen already showed up.
I had to change somesignals.
Now I get a kernel trap that does not say anything to.
Would you please be so kind and run puddletag on your system? Maybe you can help me or just say that my system is corrupted...

Here is the repo: https://github.com/chincheta0815/puddletag/tree/migration

Thanks in advance.

**Comment by keithgg** [comment]
I get the below. You'll need to update some imports to work the correct way for Py3.

>> python3 puddletag
Traceback (most recent call last):
  File "puddletag", line 329, in <module>
    migrate_settings()
  File "puddletag", line 86, in migrate_settings
    _migrate_action_shortcuts()
  File "puddletag", line 92, in _migrate_action_shortcuts
    from puddlestuff.puddleobjects import PuddleConfig
  File "/home/keith/Desktop/puddletag/source/puddlestuff/puddleobjects.py", line 20, in <module>
    import audioinfo
ImportError: No module named 'audioinfo'
