### ISSUE TITLE
Error occurred / permissions

### ISSUE THREAD

**Issue by andocromn** [keithgg/puddletag#325]
I am encountering a permissions issues, I working in a directory owned by another user and a group I belong to, the group has write access to the directory.  I have verified that my user account can write to the directory as well.  However when i attempt to save tags to files within the directory puddletag produces and error.  If sudo and change the owner of the directory to my user then it works normally.  However this should not be necessary since i belong to a group with write access to the directory

**Comment by keithgg** [comment]
Hi, can you post the full permissions on the directory. When it doesn't work and when it does?

**Comment by andocromn** [comment]
the permissions on the directory are "drwxrwsr-x", as previously mentioned, the directory is owned by a different user and a group which my user belongs to, so I do have write access.  I did do some more troubleshooting and was able to get the traceback below.  It looks like since my user account is not the owner of the directory it is unable update the modify date of the directory with os.utime.  I have been able to work around the issue by checking the "Preserve file modification times" checkbox, although this still fails, the call to setmodtime is encapsulated in a try block so the operations appear to complete successfully

```
puddletag Version: 1.0.2
Locale: en_US
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/puddlestuff/puddletag.py", line 740, in func
    update = setRowData(row, f, undo=True)
  File "/usr/lib/pymodules/python2.7/puddlestuff/tagmodel.py", line 1063, in setRowData
    undo_val = write(audio, tags, self.saveModification, justrename)
  File "/usr/lib/pymodules/python2.7/puddlestuff/util.py", line 316, in write
    os.utime(audio.dirpath, None)
OSError: [Errno 1] Operation not permitted: 
```
