### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [keithgg/puddletag#326]
Dear Keith,
Could you be so kind to generate ```.exe``` for the rest of us who use Windows, if possible?

**Comment by bernd-wechner** [comment]
It's a python application and should run just fine under Windows I'd have hoped.

But mp3tag works fine on Windows, is well supported and what puddletag sort of pays homage to anyhow (said another way, I was on Windows and used mp3tag for years and loved it, and now on Linux and use puddletag).

Given that, personally if I had any sway over Keith's time I'd encourage him to work on bugs and leave the Windows issue to a Windows user to solve if need be.

**Comment by sergeevabc** [comment]
Thank you for letting me know, @bernd-wechner.
I hoped to run it standalone, w/o need to install Python.

**Comment by bernd-wechner** [comment]
Check this out:

http://py2exe.org/

Could do what you want. Makes a standalone exe. Beauty of that too is, no need to install. Downside is to get it into your start menu you have to manually add it. I love standalones somehow as I loathe the endless series of installers in the windows world somehow (you never know how much lint they install) and a standlone exe is so clean, but has this downside that the start menu shortcut needs to be manually created as does a home for the .exe. I used to keep a C:/Program Files/Utils folder I'd dump standalone exes into and then point start menu shortcuts to.

**Comment by sergeevabc** [comment]
@bernd-wechner, since you’re pro-standalone user like me, feel free to [raise your voice against MSI].

[1]: https://github.com/jgm/pandoc/issues/3317
