### ISSUE TITLE
Stored Tags window listing ID3 tags twice

### ISSUE THREAD

**Issue by punishyourmachine** [keithgg/puddletag#331]
Hello,

Puddletag 1.2.0 in LinuxMint 18.1 Cinnamon, when viewing Stored Tags, the ID3 tags are listed twice.  I don't know if the ID3 tags are actually being stored twice in the mp3 file, or if the Stored Tags window is listing the same ID3 tag twice.

This bug has cropped up in the last few versions of Puddletag and LinuxMint with Cinnamon desktop, but I can't recall exact versions of when this first appeared.

Please view attached screen capture to see the issue.  Thank you.

![puddletag id3 tag listed twice](https://cloud.githubusercontent.com/assets/24897334/21613492/746ba6ee-d1a3-11e6-998b-8e5e7a9f9222.jpg)

**Comment by keithgg** [comment]
Did you tag that file with puddletag or something else? Can you upload it somewhere?

**Comment by punishyourmachine** [comment]
Yes, I tagged that file with puddletag.  File is here: 
https://drive.google.com/open?id=0B_t3LYMfYFG8Vm1RandYbERyUmc

**Comment by punishyourmachine** [comment]
As an update, I just now looked at an MP3 file that was NOT tagged with puddletag, and in puddletag Stored Tags window it still showed the ID3v2.3 tag listed twice, however the MP3 file also had an ID3v1.1 tag which was only listed once.

So perhaps bug is in Stored Tags window, and only applicable to ID3v2.3 tags?

**Comment by keithgg** [comment]
Thanks for the file. It was just a case of the tag getting listed twice.

**Comment by punishyourmachine** [comment]
Thank you.

**Comment by dannn-o** [comment]
I have been encountering this issue for quite some time on Linux Mint 17.3, and am wondering if there is a fairly easy way to obtain the fix (b2192d9) without having to do a 'git checkout', etc.  The PPA doesn't look like it has been updated since 11/2016, either.  Thanks.

**Comment by keithgg** [comment]
- Download the latest code from https://github.com/keithgg/puddletag/archive/master.zip
- Unzip into a folder
- cd unzipped_folder/source
- ./puddletag
