### ISSUE TITLE
puddletag not seeing mp3tag sources

### ISSUE THREAD

**Issue by Trixter69** [keithgg/puddletag#333]
I'm on a mac and I'm not sure what I'm doing wrong but Puddletag doesn't see any mp3tag .src sources I try and add to mp3tag_sources.

Here's the paths I've tried to add them to, but none of them work.

".local/puddletag/mp3tag_sources"
"source/puddlestuff/tagsources"
"source/puddlestuff/tagsources/mp3tag"

**Comment by keithgg** [comment]
They should be found if placed in ~/.config/puddletag/m3tag_sources. YMMV though. Haven't checked that they've worked in a long while.
