### ISSUE TITLE
Add support for %_counter% form Mp3Tag

### ISSUE THREAD

**Issue by nospamph4** [keithgg/puddletag#342]
Mp3Tag has a feature missing at puddletag:
%_counter% variable, available at Mp3Tag:
http://help.mp3tag.de/main_converter.html
In Tag - Filename section, in System sub-section:
%_counter% 	Counter (starting with 1)

This feature will made it possible to mass rename of selected tags/files, which will contain per file/tag auto incrementing parts, e.g. Title:"My_AudioBook_part01_chapter003".

Please, add this to puddletag.

**Comment by bernd-wechner** [comment]
If Keith can't find time to add (doubt I will), then there are two workarounds:

1) Create a new tag like "part" and populate it with number and use that. Personally I'd do it this way anyhow and never have info in the filename that is not in a tag. There's an autonumbering wizard on the toolbar for populating a tag.

2) clone the repository, add the patch and send a pull request to Keith. I did that recently with pull request https://github.com/keithgg/puddletag/pull/330, and Keith was happy to pull it. I needed that filter rather badly at the time, and so used it at as an excuse to, do this, i.e. close the repository, see if I can patch it and submit a pull request. This is of course a tad time consuming as you have to navigate the code, and would ideally be set up with an IDE like PyDev or PyCharm to help find what you need (you'd be looking at the code for existing variables are used and how and so on).

**Comment by keithgg** [comment]
It's already in, %__counter% (two underscores instead of 1).
