### ISSUE TITLE
~/puddetag/log.log

### ISSUE THREAD

**Issue by WildPhydeaux** [keithgg/puddletag#344]
Forgive the Linux noob question, but I can't find the log file anywhere. And, yes, I did look for hidden files...

![error](https://cloud.githubusercontent.com/assets/26723918/24374936/d6687584-12f3-11e7-9559-44ea360dcfd6.jpg)

**Comment by keithgg** [comment]
Hi, my bad. That error message is wholly wrong. 

The logs are in ~/.config/puddletag/log.log
