### ISSUE TITLE
Still failing to parse MP4 tags from .m4a file

### ISSUE THREAD

**Issue by uklotzde** [keithgg/puddletag#345]
Puddletag is broken in Fedora 25 after python2-mutagen-1.37 is distributed as an update. The previous commit didn't fix this issue that has already been reported and was supposed to be fixed:

https://github.com/keithgg/puddletag/issues/339

```
File "/home/uk/Projects/github/puddletag/source/puddlestuff/audioinfo/mp4.py", line 372, in link
    field_value.append(unicode(v, 'utf8'))
TypeError: coercing to Unicode: need string or buffer, int found
```

It's strange that the final else-branch where the failure occurs contains the same code as the first if-branch.

**Comment by keithgg** [comment]
Should be sorted now.

**Comment by uklotzde** [comment]
Confirmed 👍 Thank you for the prompt fix and for your work, Keith! Puddletag is an essential tool for me, THE mp3tag on Linux :)
