### ISSUE TITLE
Possible to write one tag from another?

### ISSUE THREAD

**Issue by akovia** [keithgg/puddletag#348]
I am moving from one rating system (`rating:banshee`) to another (`fmps_rating`) and want to script a way to copy one to the other. The values are identical so there is no data conversion involved.

Preferably as so.

1. if fmps_rating exists and is not empty > do nothing > exit
2. if rating:banshee exists > change field name to or copy data to fmps_rating.

I've found the [scripting reference](http://docs.puddletag.net/source/scripting.html), but have found no documentation on using it other than through pre-defined functions. Is this possible at all using puddletag, straight mutagen(mid3v2), or by any other means other than writing a program in python?

**Comment by keithgg** [comment]
Use the Text to Tag function. If the tag is empty it shouldn't get written.

http://docs.puddletag.net/source/function.html#text-to-tag
