### ISSUE TITLE
Problems with some german letters on Smartphone

### ISSUE THREAD

**Issue by mooooonbaby** [keithgg/puddletag#349]
Hi,

i've copied some audiobooks that are partly tagged with puddletag to my smartphone (a very cheap doogee x5 max pro). because the internal audio player has the best interface to navigate audiobooks i use this. the player has problems with some german letters (https://en.wikipedia.org/wiki/Umlaut_(linguistics) - i don't know the english word for that :-( ). instead of the letter the app shows 2 other letters that i've never seen on a keyboard. maybe this is a problem with the app - but when i tag the files with mp3tag using wine the apps displays the letters correct.

i can use mp3tag off course but using this program with wine isn't fun.

**Comment by keithgg** [comment]
My hunch is that your phone doesn't support UTF8 encoding. Mp3tag supports writing to more than just utf8, whereas puddletag doesn't [nor do I have any plans to].

Do me a favour. Tag a file (link at bottom) with both mp3tag and puddletag and send them to me. Of course after verifying that it displays incorrectly on your phone.

https://github.com/quodlibet/mutagen/blob/master/tests/data/silence-44-s.mp3
