### ISSUE TITLE
Action patterns: Problem creating a dynamic directory structure

### ISSUE THREAD

**Issue by HumanGerm** [keithgg/puddletag#368]
I have just discovered this program after using mp3tag under wine for years!  Much kudos!  It is as easy to use as mp3tag, and in some ways, more so!

I like to create single replace patterns that will work with everything!  I also like to sort discs into separate directories for multi-disc albums:

e.g. the following album has directory structure:

```
ls -l ~/Music/John Foxx/[2014] The Virgin years 1980-1985 [FLAC 44-lossless]/

Disc 1, Metamatic
Disc 2, The garden
Disc 3, The golden section
Disc 4, In mysterious ways
Disc 5, FusionFisson

```
... and within each of these is the contents of its disc.

I have the following pattern to move everything into place (which should work with both single and multi-disc albums: 

`~/Music/%albumartist%/[%year%] %album% [%__filetype% $left(%__frequency%,2)$if($neql(%__filetype%,FLAC),,-lossless)]/$if(%discnumber%,disc %discnumber%,)$if(%disctitle%,"," %disctitle%,)$if(%disctitle% or `%discnumber%,"/",)$num(%track%,2)` %title%
`
Renders a track as:

`~/Music/John Foxx/[2014] The Virgin years 1980-1985 [FLAC 44-lossless]/Disc 1, Metamatic01 Plaza.flac

but should look like:

`~/Music/John Foxx/[2014] The Virgin years 1980-1985 [FLAC 44-lossless]/Disc 1, Metamatic/01 Plaza.flac
`
... note the missing directory `/` hierarchy.  The `$if(%disctitle% or %discnumber%,"/",)` should create a directory, but the `/` is being stripped out of the `$if()` function. 

I have tried a workaround, to make the `/` non-dynamic, it works with multi-disc releases, but breaks single disc albums:

`~/Music/%albumartist%/[%year%] %album% [%__filetype% $left(%__frequency%,2)$if($neql(%__filetype%,FLAC),,-lossless)]/$if(%discnumber%,disc %discnumber%,)$if(%disctitle%,"," %disctitle%,)/$num(%track%,2) %title%
`
Renders the following for a single disc album:

`~/Music/John Foxx/[1993] Metamatic [FLAC 44-lossless]/""/Disc 1, 01 Plaza.flac
`
... creating an extra directory called ""

Is there a way to render a `/` directory within an `$if()` statement?  My current workaround is to use 2 patterns, one for multi-disc releases, and the other for single discs.  Sorry if I appear to be too much of a perfectionist!  I love this program and see myself relying on it for all of my tagging needs!  Thank you for all of your good work!

I hope that this make sense!  Happy to provide any further information if needed!

Best wishes, Stewart

**Comment by keithgg** [comment]
Hi Stewart

Thanks for this. Unfortunately, there's no way to add the / as part of the $if statement at the moment. This is intentional, because the case where you get a separator (eg. as part of the track name) happened more often than the reverse.
