### ISSUE TITLE
Puddletag can't read AAC in .M4A files

### ISSUE THREAD

**Issue by najjara** [keithgg/puddletag#375]
When trying to add .m4a files (Apple iTunes) encoded in AAC the program doesn't add them (does nothing). This is the same whether dragging and dropping the files, or choosing a directory.

Editing MP3s works without a problem.

Here's the terminal output when I add a .m4a:

```
puddletag Version: 1.2.0
Fontconfig warning: "/home/najjara/.config/fontconfig/fonts.conf", line 36: Expression doesn't take any effects for delete and delete_all
Locale: en_US
Object::disconnect: Unexpected null parameter
An error occured.
/home/najjara/something.m4a
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/puddlestuff/puddleobjects.py", line 675, in gettag
    return audioinfo.Tag(f)
  File "/usr/lib/python2.7/site-packages/puddlestuff/tagmodel.py", line 298, in ReplacementTag
    return extensions[ext][1](filename)
  File "/usr/lib/python2.7/site-packages/puddlestuff/tagmodel.py", line 151, in __init__
    super(ModelTag, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/puddlestuff/audioinfo/mp4.py", line 190, in __init__
    util.MockTag.__init__(self, filename)
  File "/usr/lib/python2.7/site-packages/puddlestuff/audioinfo/util.py", line 663, in __init__
    self.link(filename)
  File "/usr/lib/python2.7/site-packages/puddlestuff/audioinfo/mp4.py", line 366, in link
    isinstance(v, unicode) else v for v in audio[key]]
TypeError: coercing to Unicode: need string or buffer, int found
```
Here's the relevant metadata from that file:

```
$ mediainfo '/home/najjara/something.m4a' 

General
Complete name                            : /home/najjara/something.m4a
Format                                   : MPEG-4
Format profile                           : Apple audio with iTunes info
Codec ID                                 : M4A  (M4A /mp42/isom)
Overall bit rate mode                    : Variable
Overall bit rate                         : 285 kb/s
Flavour                                  : 2:256

Audio
ID                                       : 1
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : mp4a-40-2
Bit rate mode                            : Variable
Bit rate                                 : 256 kb/s
Maximum bit rate                         : 395 kb/s
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 44.1 kHz
Frame rate                               : 43.066 FPS (1024 SPF)
Compression mode                         : Lossy

```
Installed from Arch packages
```
puddletag 1.2.0
PyQt 4.12.1
Mutagen 1.38
Pyparsing 2.2.0
Qt 4.8.7
```

**Comment by thwaller** [comment]
This appears to be the same, or at least very similar, to my issue here:
https://github.com/keithgg/puddletag/issues/374
We also appear to have some variations on versions reported.

I had not tried MP3 files, just M4A... which matches your statements here, AAC. Did you have Puddletag working prior? For me, this changed within the last few days from working to not.

**Comment by kronstadt21** [comment]
Experiencing the same issues after upgrade from Ubuntu 17.04 to 17.10.

**Comment by keithgg** [comment]
Closing this for now. Fixed in master already. Need to make a new release.

**Comment by thwaller** [comment]
@keithgg - I know this is not really the proper place for such a post, but before you make that fixed version, there is an error that comes when executing the current version from master in terminal:
Object::disconnect: Unexpected null parameter
The program runs fine as far as I can see though.

**Comment by RafaelLinux** [comment]
I'm using Puddletag 1.2.0 (two years ago from this post) and still Puddletag doesn't show my ".m4a" files!!!!

What's wrong with this?

Thank you

**Comment by sandrotosi** [comment]
> I'm using Puddletag 1.2.0 (two years ago from this post) and still Puddletag doesn't show my ".m4a" files!!!!

there's a new release of puddletag, version 2.0.1: please use that and let us know if it's still an issue

**Comment by thwaller** [comment]
FYI- After installing new version...

$ puddletag  
  File "/usr/bin/puddletag", line 198  
    print 'No fontsize specified.'  
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('No fontsize specified.')?

**Comment by sandrotosi** [comment]
> FYI- After installing new version...
> 
> $ puddletag
> File "/usr/bin/puddletag", line 198
> print 'No fontsize specified.'
> SyntaxError: Missing parentheses in call to 'print'. Did you mean print('No fontsize specified.')?

you're definitely not using the right version: https://github.com/puddletag/puddletag/blob/2.0.1/source/puddletag#L198 line 198 in 2.0.1 is different.

> I tried fixing the issue quickly myself, but the errors kept coming. I stopped at this:
> $ ./puddletag
> Traceback (most recent call last):
> File "./puddletag", line 325, in
> from puddlestuff import resource #Needs to be first as other modules use it.
> ModuleNotFoundError: No module named 'puddlestuff'

to run it from git, you need to execute: `PYTHONPATH=source/ ./source/puddletag` at the root of the cloned repo

**Comment by RafaelLinux** [comment]
> > I'm using Puddletag 1.2.0 (two years ago from this post) and still Puddletag doesn't show my ".m4a" files!!!!
> 
> there's a new release of puddletag, version 2.0.1: please use that and let us know if it's still an issue

Unfortunately, it seems Puddletag OpenSUSE maintainers doesn't care too much Puddletag. There is not version newer than 1.2 compiled for any OpenSUSE version  :(

**Comment by thwaller** [comment]
> > > I'm using Puddletag 1.2.0 (two years ago from this post) and still Puddletag doesn't show my ".m4a" files!!!!
> > 
> > 
> > there's a new release of puddletag, version 2.0.1: please use that and let us know if it's still an issue
> 
> Unfortunately, it seems Puddletag OpenSUSE maintainers doesn't care too much Puddletag. There is not version newer than 1.2 compiled for any OpenSUSE version :(

I cannot speak for OpenSUSE, but with Ubuntu, release updates are not really the job of the maintainers, they compile/collect the packages at the time of the Ubuntu release, and as needed will update, mostly for security reasons. To get updates, I often need to use the developers PPA, or steal from the PPA set for the later releases.

This was the issue I had ... I installed from the Ubuntu PPA, not knowing I was using the Ubuntu repos for Puddletag.

**Comment by sandrotosi** [comment]
it is not fair to complain about maintainers who use their spare time to provide software to you, for free.

If you think you can do a better job, please step up and do it for everyone; else maybe send the mainteiners a "thank you for your work" email -- sometimes compliments can make wonders (instead of just whining users).

do not reply again if the only words you have to say are complains for distro maintainer.

**Comment by thwaller** [comment]
> it is not fair to complain about maintainers who use their spare time to provide software to you, for free.
> 
> If you think you can do a better job, please step up and do it for everyone; else maybe send the mainteiners a "thank you for your work" email -- sometimes compliments can make wonders (instead of just whining users).
> 
> do not reply again if the only words you have to say are complains for distro maintainer.

Where exactly is that being directed? Quite harsh, we should all be polite and lead by example.

**Comment by sandrotosi** [comment]
to the 2 of you. dont mistake being direct with being harsh.

this ticket has been closed for years; i'm gonna lock the conversation as i had enough. please report real, new problems as new issues.
