### ISSUE TITLE
Issue with module PyQt4.QtSvg

### ISSUE THREAD

**Issue by luciolucia** [keithgg/puddletag#376]
It's two days I'm fighting to install this great tag-editor on my elementary OS 0.4.1 Loki (64-bit) machine. After a clean re-install of PyQt4 I was hoping to have luck, instead - even though I've been able to successfully install it - when I execute it I get the following error:
```
myusername@myPCname:/usr/local/bin$ puddletag
Traceback (most recent call last):
  File "/usr/local/bin/puddletag", line 328, in <module>
    migrate_settings()
  File "/usr/local/bin/puddletag", line 86, in migrate_settings
    _migrate_action_shortcuts()
  File "/usr/local/bin/puddletag", line 92, in _migrate_action_shortcuts
    from puddlestuff.puddleobjects import PuddleConfig
  File "/usr/local/lib/python2.7/dist-packages/puddlestuff/puddleobjects.py", line 10, in <module>
    from PyQt4.QtSvg import *
ImportError: No module named QtSvg
```
Any idea on how to solve this? I'm going crazy :=
Thanks in advance, Lucia

**Comment by dglava** [comment]
Do you have the `libqt4-svg` package installed?
I don't use Ubuntu, but after quickly checking their online package details, it seems that that package provides the SVG library for Qt4. Additionally you might need `python-pyside.qtsvg` which provides Python bindings for it (but another package could also provide it, check your package manager).
