### ISSUE TITLE
How to use the find/replace via regexp?

### ISSUE THREAD

**Issue by mrjayviper** [keithgg/puddletag#381]
hello. I want to remove some characters on the title via REGEXP but I cannot get it to work.

example:
track title= No. 1 Fan (WTF*ck version) 

I want to move the dot and the asterisk via regexp. I can do this by listing all the characters and using regular replace but REGEXP would be much more efficient especially if the characters I want to remove increases.

Can you please help? Thanks!

ps. I was going to ask the forums but I registered twice and I never received the activation emai. I checked the spam box and it's not there. Thanks again!

**Comment by evanescente-ondine** [comment]
Same here !
My file names are like this:
Correct-name-[11*random character excluding white space].opus
The correct regexp what's between the correct name and ".opus" is: -(\S{11})(?=\.opus)
I tested it on https://pythex.org/ !
But it won't do a thing. Why ? I have Puddletag 1.2.0 PyQt 4.11.4 Mutagen 1.36 Pyparsing 2.1.10
