### ISSUE TITLE
trying to remove dots in front of title tag. seems puddletag can't see it

### ISSUE THREAD

**Issue by mrjayviper** [keithgg/puddletag#382]
so I have this track with the title "...And justice for all."

there are 3 dots in front and a dot at the end.

using regexp find/replace, I tried:

[.] : this replaced only the dot at the end

[.]|[.] | same results as above

I tried both reg expressions on online regexp testers and they're suppose to work.

Any ideas how it can be done? perhaps a bug?

**Comment by keithgg** [comment]
Your regular expression doesn't match what you trying to achieve Try this:

    ^\.{3}
