### ISSUE TITLE
Hidpi support?

### ISSUE THREAD

**Issue by amithiel** [keithgg/puddletag#400]
Hey there!
I'm using ubuntu mate 18.04 on a retina display, any plans for making puddle tag hidpi compatible? 
Sure hope so..because this one is the best editor out there... 
cheers

**Comment by dglava** [comment]
Porting it to Qt5 will solve that, I think. See this #313.

**Comment by XVilka** [comment]
Related also https://github.com/keithgg/puddletag/issues/380
