### ISSUE TITLE
AUR, Manjaro (Arch): unable to satisfy dependency 'python2-pillow6'

### ISSUE THREAD

**Issue by atomGit** [keithgg/puddletag#474]
there doesn't seem to be a python2-pillow6 package in the AUR

i got the error today when an upgrade was announced

**Comment by miniworm** [comment]
Solution for your problem is to use newly created AppImagge which will run on Fedora 32, Ubuntu 20.04 and any other new distro. Jut take a look at #464

**Comment by atomGit** [comment]
this resolved itself after one of the updates - i don't know which package(s)
